from node:22.21.0-alpine3.21

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 5000

CMD ["pnpm", "dev", "--host", "0.0.0.0"]