services:
  db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./backend/db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    environment:
      - PORT=${BACKEND_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - TEST_POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - TEST_POSTGRES_USER=${TEST_POSTGRES_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_POSTGRES_DB}
      - TEST_POSTGRES_HOST=${TEST_POSTGRES_HOST}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_RT_TTL=${BACKEND_JWT_RT_TTL}
      - CORS_ALLOWED=${BACKEND_CORS_ALLOWED}
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile.preprod
    environment:
      - VITE_API_URL=${FRONTEND_VITE_API_URL}
    ports:
      - ${FRONTEND_PORT}:5000
